[build]
  command = ""
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/auth"
  status = 200
